# Generated by Django 4.1 on 2022-10-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_sub_timetable1_eighth_period_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_timetable1',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable10',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable11',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable12',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable13',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable14',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable15',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable16',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable17',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable18',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable19',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable2',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable20',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable21',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable22',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable23',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable24',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable25',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable26',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable27',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable28',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable29',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable3',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable30',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable31',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable32',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable33',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable34',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable35',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable36',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable37',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable38',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable39',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable4',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable40',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable5',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable6',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable7',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable8',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_timetable9',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
    ]
