# Generated by Django 4.1 on 2022-10-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_timetable_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Shortname',
            new_name='Acronym',
        ),
    ]
