# Generated by Django 4.1 on 2022-10-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_sub_timetables_timetable_remove_data_prx_table_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_prx',
            name='Acronym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
    ]
