# Generated by Django 4.1 on 2022-10-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_data_prx_table_id_alter_data_prx_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.data_prx'),
        ),
    ]
