# Generated by Django 4.1 on 2022-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_sub_data_prx1_eighth_proxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_data_prx1',
            name='Table_Id',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx10',
            name='Table_Id',
            field=models.IntegerField(default=10, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx11',
            name='Table_Id',
            field=models.IntegerField(default=11, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx12',
            name='Table_Id',
            field=models.IntegerField(default=12, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx13',
            name='Table_Id',
            field=models.IntegerField(default=13, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx14',
            name='Table_Id',
            field=models.IntegerField(default=14, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx15',
            name='Table_Id',
            field=models.IntegerField(default=15, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx16',
            name='Table_Id',
            field=models.IntegerField(default=16, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx17',
            name='Table_Id',
            field=models.IntegerField(default=17, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx18',
            name='Table_Id',
            field=models.IntegerField(default=18, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx19',
            name='Table_Id',
            field=models.IntegerField(default=19, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx2',
            name='Table_Id',
            field=models.IntegerField(default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx20',
            name='Table_Id',
            field=models.IntegerField(default=20, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx21',
            name='Table_Id',
            field=models.IntegerField(default=21, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx22',
            name='Table_Id',
            field=models.IntegerField(default=22, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx23',
            name='Table_Id',
            field=models.IntegerField(default=23, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx24',
            name='Table_Id',
            field=models.IntegerField(default=24, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx25',
            name='Table_Id',
            field=models.IntegerField(default=25, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx26',
            name='Table_Id',
            field=models.IntegerField(default=26, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx27',
            name='Table_Id',
            field=models.IntegerField(default=27, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx28',
            name='Table_Id',
            field=models.IntegerField(default=28, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx29',
            name='Table_Id',
            field=models.IntegerField(default=29, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx3',
            name='Table_Id',
            field=models.IntegerField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx30',
            name='Table_Id',
            field=models.IntegerField(default=30, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx31',
            name='Table_Id',
            field=models.IntegerField(default=31, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx32',
            name='Table_Id',
            field=models.IntegerField(default=32, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx33',
            name='Table_Id',
            field=models.IntegerField(default=33, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx34',
            name='Table_Id',
            field=models.IntegerField(default=34, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx35',
            name='Table_Id',
            field=models.IntegerField(default=35, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx36',
            name='Table_Id',
            field=models.IntegerField(default=36, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx37',
            name='Table_Id',
            field=models.IntegerField(default=37, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx38',
            name='Table_Id',
            field=models.IntegerField(default=38, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx39',
            name='Table_Id',
            field=models.IntegerField(default=39, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx4',
            name='Table_Id',
            field=models.IntegerField(default=4, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx5',
            name='Table_Id',
            field=models.IntegerField(default=5, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx6',
            name='Table_Id',
            field=models.IntegerField(default=6, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx7',
            name='Table_Id',
            field=models.IntegerField(default=7, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx8',
            name='Table_Id',
            field=models.IntegerField(default=8, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prx9',
            name='Table_Id',
            field=models.IntegerField(default=9, max_length=2),
        ),
        migrations.AddField(
            model_name='sub_data_prxs',
            name='Table_Id',
            field=models.IntegerField(default=40, max_length=2),
        ),
    ]
