# Generated by Django 4.1 on 2022-11-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_sub_data_prx1_table_id_sub_data_prx10_table_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_data_prxs',
            name='Table_Id',
        ),
        migrations.AddField(
            model_name='sub_data_prx40',
            name='Table_Id',
            field=models.IntegerField(default=40, max_length=2),
        ),
        migrations.AlterField(
            model_name='data_prx',
            name='Table_Id',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40')], max_length=2, unique=True),
        ),
    ]
