# Generated by Django 4.1 on 2023-05-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_delete_sub_timetables_alter_data_prx_table_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('Teacher', models.CharField(max_length=50)),
                ('Acronym', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Proxy', models.IntegerField(default=0, max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='data_prx',
            name='Table_Id',
            field=models.CharField(default=5, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Table_Id',
            field=models.CharField(default=15, max_length=2, unique=True),
        ),
    ]
