# Generated by Django 4.1 on 2022-09-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('Teacher', models.CharField(max_length=50)),
                ('Shortname', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
