# Generated by Django 4.1 on 2022-09-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_1', models.CharField(max_length=5)),
                ('period_2', models.CharField(max_length=5)),
                ('period_3', models.CharField(max_length=5)),
                ('period_4', models.CharField(max_length=5)),
                ('period_5', models.CharField(max_length=5)),
                ('period_6', models.CharField(max_length=5)),
                ('period_7', models.CharField(max_length=5)),
                ('period_8', models.CharField(max_length=5)),
                ('period_9', models.CharField(max_length=5)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.timetable')),
            ],
        ),
    ]
