# Generated by Django 4.1 on 2022-09-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sub_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_timetable',
            name='id',
        ),
        migrations.AlterField(
            model_name='sub_timetable',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.timetable'),
        ),
    ]
