# Generated by Django 4.1 on 2022-09-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sub_timetabl14_sub_timetabl34_sub_timetable1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_TimeTabl14',
            new_name='sub_TimeTable14',
        ),
        migrations.RenameModel(
            old_name='sub_TimeTabl34',
            new_name='sub_TimeTable34',
        ),
    ]
