# Generated by Django 4.0.4 on 2022-10-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sub_timetabl14_sub_timetable14_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_timetable42',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable43',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable44',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable45',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable46',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable47',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable48',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable49',
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='sub_timetable50',
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable41',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable42',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable43',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable44',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable45',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable46',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable47',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable48',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable49',
        ),
        migrations.DeleteModel(
            name='sub_TimeTable50',
        ),
    ]
