# Generated by Django 4.0.4 on 2022-10-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_data_prx_acronym_alter_data_prx_teacher_and_more'),
        ('home', '0027_alter_sub_timetable1_eighth_period_1_and_more'),
    ]

    operations = [
    ]
