# Generated by Django 4.0.4 on 2022-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_data_prx_acronym_alter_data_prx_table_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_timetable1',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable10',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable11',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable12',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable13',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable14',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable15',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable16',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable17',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable18',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable19',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable2',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable20',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable21',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable22',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable23',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable24',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable25',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable26',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable27',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable28',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable29',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable3',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable30',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable31',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable32',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable33',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable34',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable35',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable36',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable37',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable38',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable39',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable4',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable40',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable5',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable6',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable7',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable8',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='sub_timetable9',
            name='ZERO',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
