# Generated by Django 4.1 on 2022-11-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_sub_data_prx1_eighth_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
