# Generated by Django 4.1 on 2022-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_sub_data_prx1_eighth_proxy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx12',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx13',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx14',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx15',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx16',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx17',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx18',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx19',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx20',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx21',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx22',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx23',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx24',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx25',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx26',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx27',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx28',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx29',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx30',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx31',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx32',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx33',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx34',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx35',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx36',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx37',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx38',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx39',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx40',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
