# Generated by Django 4.1 on 2022-12-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_sub_timetable41_sub_timetable42_sub_timetable43_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx1',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx10',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx11',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx2',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx3',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx4',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx5',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx6',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx7',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx8',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='EIGHTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FIFTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FIRST_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='FOURTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='NINETH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SECOND_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SEVENTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='SIXTH_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_data_prx9',
            name='THIRD_proxy',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Table_Id',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50')], max_length=2, unique=True),
        ),
    ]
