# Generated by Django 4.1 on 2023-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_sub_data_prx1_eighth_proxy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_TimeTables',
        ),
        migrations.AlterField(
            model_name='data_prx',
            name='Table_Id',
            field=models.CharField(default=[1, 8, 6, 3, 4, 2, 9, 10, 7, 5], max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Table_Id',
            field=models.CharField(default=[8, 40, 28, 41, 2, 26, 19, 32, 5, 20, 34, 14, 45, 3, 48, 10, 31, 47, 15, 16, 38, 33, 6, 17, 46, 9, 1, 21, 43, 4, 7, 18, 24, 39, 30, 22, 25, 49, 36, 35, 42, 44, 29, 23, 11, 13, 37, 12, 27], max_length=2, unique=True),
        ),
    ]
