# Generated by Django 4.1 on 2023-05-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_data_prx_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Table_Id',
            field=models.IntegerField(max_length=2, unique=True),
        ),
    ]
