# Generated by Django 4.1 on 2023-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_alter_timetable_acronym_alter_timetable_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Teacher', models.CharField(max_length=50)),
                ('Acronym', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Table_Id', models.IntegerField(max_length=2, unique=True)),
            ],
        ),
    ]
